# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
        environment:
          JDBC_DATABASE_URL: "jdbc:mysql://127.0.0.1/findeasily?useSSL=false&useUnicode=true&characterEncoding=utf-8"
          JDBC_DATABASE_USERNAME: user
          JDBC_DATABASE_PASSWORD: Passw0d1
          REDIS_HOST: 127.0.0.1
          REDIS_PASSWORD: Passw0d1

      - image: circleci/mariadb:10.4
        environment:
          MYSQL_DATABASE: findeasily
          MYSQL_ROOT_PASSWORD: password
          MYSQL_PASSWORD: Passw0d1
          MYSQL_USER: user

      - image: circleci/redis:5.0-alpine3.8
        command: redis-server --requirepass Passw0d1

      - image: webcenter/activemq:5.14.3
        volumes: ["activemq-data:/opt/activemq/conf", "activemq-data:/data/activemq", "activemq-data:/var/log/activemq"]
        environment:
          ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
          ACTIVEMQ_ADMIN_LOGIN: admin
          ACTIVEMQ_ADMIN_PASSWORD: password
          ACTIVEMQ_WRITE_LOGIN: write
          ACTIVEMQ_WRITE_PASSWORD: password
          ACTIVEMQ_READ_LOGIN: read
          ACTIVEMQ_READ_PASSWORD: password
          ACTIVEMQ_JMX_LOGIN: jmx
          ACTIVEMQ_JMX_PASSWORD: password
          ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
          ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
          ACTIVEMQ_ENABLED_SCHEDULER: "true"
          ACTIVEMQ_MIN_MEMORY: 512
          ACTIVEMQ_MAX_MEMORY: 2048

    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Maven Build & Test
          command: |
            mvn clean package

      - store_test_results:
          path: target/surefire-reports

      - persist_to_workspace:
          root: target
          paths:
            - website.jar

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo/target
      - run:
          name: Deploy Over SSH
          command: |
            scp -o "StrictHostKeyChecking no" ~/repo/target/website.jar $SSH_USER@$SSH_HOST:/var/findeasily/
      - run:
          name: restart website
          command: |
            ssh $SSH_USER@$SSH_HOST "systemctl restart website.service"


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
